Update flarum-tags.yml
Csineneo/lang-traditional-chinese pull request #1
Opened 2020-01-03 17:49 UTC by chiyi4488

您好，我認為「標籤」一詞比「節點」來的好，可能是因為我不太知道「節點」是什麼意思😅，且我覺得「標籤」大多數人比較知道這個詞，因為不管是微軟、谷歌，就我所知應該都是用「標籤」的。

P.S. 我找「標籤」管理找好久才發現原來叫「節點」XD

希望能修改此詞

感謝您的付出:)

2020-03-14 17:16 UTC, pan93412 approved these changes

2020-03-14 17:16 UTC, pan93412 commented
@Csineneo fyi.

2020-03-14 17:17 UTC, pan93412 requested changes

2020-03-14 17:17 UTC, pan93412 commented on locale/flarum-tags.yml
>        delete_tag_confirmation: "確定要刪除此幾點？此節點下的貼文將不會被刪除。"
幾點 -> 標籤

2020-03-15 02:54 UTC, Csineneo commented on locale/flarum-tags.yml
>        delete_tag_confirmation: "確定要刪除此幾點？此節點下的貼文將不會被刪除。"
typo 已修正

2020-03-15 02:55 UTC, Csineneo commented
個人偏好「節點」，不做更改

2020-03-15 02:55 UTC, closed without merging